/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "c_synth.v:1" *)
module c_synth(clk, reset, enable, D_synth, mode, Q_synth, rco_synth, load_synth);
  (* src = "c_synth.v:18" *)
  wire _000_;
  (* src = "c_synth.v:18" *)
  wire [3:0] _001_;
  (* src = "c_synth.v:18" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  (* src = "c_synth.v:2" *)
  input clk;
  (* src = "c_synth.v:4" *)
  input enable;
  (* src = "c_synth.v:5" *)
  input [3:0] D_synth;
  (* src = "c_synth.v:9" *)
  output load_synth;
  (* src = "c_synth.v:6" *)
  input [1:0] mode;
  (* src = "c_synth.v:7" *)
  output [3:0] Q_synth;
  (* src = "c_synth.v:8" *)
  output rco_synth;
  (* src = "c_synth.v:3" *)
  input reset;
  NOT _055_ (
    .A(enable),
    .Y(_003_)
  );
  NAND _056_ (
    .A(mode[1]),
    .B(mode[0]),
    .Y(_004_)
  );
  NOR3 _057_ (
    .A(_004_),
    .B(reset),
    .C(_003_),
    .Y(_000_)
  );
  NOR _058_ (
    .A(reset),
    .B(_003_),
    .Y(_005_)
  );
  NAND _059_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  NOT _060_ (
    .A(Q_synth[3]),
    .Y(_007_)
  );
  NOT _061_ (
    .A(mode[0]),
    .Y(_008_)
  );
  NAND _062_ (
    .A(mode[1]),
    .B(_008_),
    .Y(_009_)
  );
  NAND3 _063_ (
    .A(Q_synth[2]),
    .B(Q_synth[1]),
    .C(Q_synth[0]),
    .Y(_010_)
  );
  NOR3 _064_ (
    .A(_010_),
    .B(_009_),
    .C(_007_),
    .Y(_011_)
  );
  NOR3 _065_ (
    .A(Q_synth[2]),
    .B(Q_synth[1]),
    .C(Q_synth[0]),
    .Y(_012_)
  );
  NOR3 _066_ (
    .A(Q_synth[3]),
    .B(mode[1]),
    .C(_008_),
    .Y(_013_)
  );
  NAND _067_ (
    .A(_013_),
    .B(_012_),
    .Y(_014_)
  );
  NOT _068_ (
    .A(mode[1]),
    .Y(_015_)
  );
  NOT _069_ (
    .A(Q_synth[2]),
    .Y(_016_)
  );
  NOR _070_ (
    .A(Q_synth[1]),
    .B(Q_synth[0]),
    .Y(_017_)
  );
  NOR3 _071_ (
    .A(_017_),
    .B(_007_),
    .C(_016_),
    .Y(_018_)
  );
  NAND3 _072_ (
    .A(_018_),
    .B(_015_),
    .C(_008_),
    .Y(_019_)
  );
  NAND _073_ (
    .A(_019_),
    .B(_014_),
    .Y(_020_)
  );
  NOR _074_ (
    .A(_020_),
    .B(_011_),
    .Y(_021_)
  );
  NOR _075_ (
    .A(_021_),
    .B(_006_),
    .Y(_002_)
  );
  NAND _076_ (
    .A(_000_),
    .B(D_synth[0]),
    .Y(_022_)
  );
  NOT _077_ (
    .A(Q_synth[0]),
    .Y(_023_)
  );
  NAND3 _078_ (
    .A(_004_),
    .B(_005_),
    .C(_023_),
    .Y(_024_)
  );
  NAND _079_ (
    .A(_024_),
    .B(_022_),
    .Y(_001_[0])
  );
  NAND _080_ (
    .A(Q_synth[1]),
    .B(Q_synth[0]),
    .Y(_025_)
  );
  NOT _081_ (
    .A(_025_),
    .Y(_026_)
  );
  NOR3 _082_ (
    .A(_026_),
    .B(_009_),
    .C(_017_),
    .Y(_027_)
  );
  NOR _083_ (
    .A(_026_),
    .B(_017_),
    .Y(_028_)
  );
  NOR _084_ (
    .A(_028_),
    .B(mode[1]),
    .Y(_029_)
  );
  NOT _085_ (
    .A(D_synth[1]),
    .Y(_030_)
  );
  NOR _086_ (
    .A(_004_),
    .B(_030_),
    .Y(_031_)
  );
  NOR3 _087_ (
    .A(_031_),
    .B(_029_),
    .C(_027_),
    .Y(_032_)
  );
  NOR3 _088_ (
    .A(_032_),
    .B(reset),
    .C(_003_),
    .Y(_001_[1])
  );
  NOR _089_ (
    .A(_017_),
    .B(_016_),
    .Y(_033_)
  );
  NOR _090_ (
    .A(_033_),
    .B(_012_),
    .Y(_034_)
  );
  NOR3 _091_ (
    .A(_034_),
    .B(mode[1]),
    .C(_008_),
    .Y(_035_)
  );
  NAND3 _092_ (
    .A(D_synth[2]),
    .B(mode[1]),
    .C(mode[0]),
    .Y(_036_)
  );
  NAND _093_ (
    .A(_025_),
    .B(_016_),
    .Y(_037_)
  );
  NOR _094_ (
    .A(_025_),
    .B(_016_),
    .Y(_038_)
  );
  NOR _095_ (
    .A(_038_),
    .B(_009_),
    .Y(_039_)
  );
  NAND _096_ (
    .A(_039_),
    .B(_037_),
    .Y(_040_)
  );
  NAND3 _097_ (
    .A(_034_),
    .B(_015_),
    .C(_008_),
    .Y(_041_)
  );
  NAND3 _098_ (
    .A(_041_),
    .B(_040_),
    .C(_036_),
    .Y(_042_)
  );
  NOR _099_ (
    .A(_042_),
    .B(_035_),
    .Y(_043_)
  );
  NOR3 _100_ (
    .A(_043_),
    .B(reset),
    .C(_003_),
    .Y(_001_[2])
  );
  NOR3 _101_ (
    .A(_012_),
    .B(mode[1]),
    .C(_008_),
    .Y(_044_)
  );
  NOR _102_ (
    .A(_044_),
    .B(_039_),
    .Y(_045_)
  );
  NOR _103_ (
    .A(_045_),
    .B(_007_),
    .Y(_046_)
  );
  NAND _104_ (
    .A(_015_),
    .B(_008_),
    .Y(_047_)
  );
  NOR _105_ (
    .A(_033_),
    .B(Q_synth[3]),
    .Y(_048_)
  );
  NOR3 _106_ (
    .A(_048_),
    .B(_018_),
    .C(_047_),
    .Y(_049_)
  );
  NOR3 _107_ (
    .A(_010_),
    .B(_015_),
    .C(mode[0]),
    .Y(_050_)
  );
  NAND _108_ (
    .A(_050_),
    .B(_007_),
    .Y(_051_)
  );
  NAND3 _109_ (
    .A(D_synth[3]),
    .B(mode[1]),
    .C(mode[0]),
    .Y(_052_)
  );
  NAND3 _110_ (
    .A(_052_),
    .B(_051_),
    .C(_014_),
    .Y(_053_)
  );
  NOR3 _111_ (
    .A(_053_),
    .B(_049_),
    .C(_046_),
    .Y(_054_)
  );
  NOR3 _112_ (
    .A(_054_),
    .B(reset),
    .C(_003_),
    .Y(_001_[3])
  );
  DFF _113_ (
    .C(clk),
    .D(_001_[0]),
    .Q(Q_synth[0])
  );
  DFF _114_ (
    .C(clk),
    .D(_001_[1]),
    .Q(Q_synth[1])
  );
  DFF _115_ (
    .C(clk),
    .D(_001_[2]),
    .Q(Q_synth[2])
  );
  DFF _116_ (
    .C(clk),
    .D(_001_[3]),
    .Q(Q_synth[3])
  );
  DFF _117_ (
    .C(clk),
    .D(_002_),
    .Q(rco_synth)
  );
  DFF _118_ (
    .C(clk),
    .D(_000_),
    .Q(load_synth)
  );
endmodule
